### PR TITLE
Added ComicsDB module.

### PR DESCRIPTION
**Pull request by Mav7**

### CODE REVIEW

**Comment by skippyPeanutButter** [comment]
Any particular reason you made this a module?

**Comment by Mav7** [comment]
Yeah I put the details in that last ticket I moved to done. I remember you
mentioned creating a separate class for doing the stuff that certain
methods in ComicsDir was doing in relation to the database in this case it
was one thing. I pressed it into service last night our rails app that we
use to try out features of the gem
<https://github.com/Mav7/CanvasComicsApp/commit/f4bf742b54b66a885b78bfc72d845b9fd1dcc1e0>.
Do you think it's a bad idea? Or it should be changed?

**Comment by Mav7** [comment]
- The idea behind this is that if the programmer chooses to use a
   database we don't want to pull images from the DB. We want to just make an
   association between comic title in our DB to folders or files in the some
   folder where image assets are held.

So In the CanvasComicsApp(I changed the name from bigwin) I'm using a
database to list 3 titles but I only have image folders for two. So the
third returns a 404 page because there are no images to return to
show.html. I used that method in the gem to see if there is an image folder
name that matches the title in the database.

**Comment by Mav7** [comment]
Oh yeah and here's the app on heroku http://canvascomics.herokuapp.com/

**Pull request merged**
